[package]
name = "osql_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["debug", "display"] }
logos = "0.15.0"
ntest = "0.9.3"
thiserror = "2.0.12"
